### ISSUE TITLE
npm start之后会报错

### ISSUE THREAD

**Issue by whyyue** [alibaba/GGEditor#488]
## 版本

> 请检查问题是否存在于最新版本中
clone下来的master上。

## 环境

> 系统、浏览器、React 等版本信息
MacOS Mojave 10.14.6 (18G103) 
chorme 80.0.3987.163
就是当前repo的master分支的react版本。

## 重现链接

> 最小化重现错误以便精准定位问题，例如：[Flow](https://codesandbox.io/s/m2v96ok1p) / [Mind](https://codesandbox.io/s/1z6vp25xz3)

## 重现步骤
1、git clone
2、cd GGEditor
3、npm install
4、npm start

> 清晰的重现步骤以便迅速定位问题

## 期望的结果是什么
正常运行起来且跑在localhost的8080端口

## 实际的结果是什么
console的log如下：
> gg-editor@3.1.1 start /Users/wanghongyue/Documents/GGEditor
> node ./scripts/start.js

? Which example do you want to run? flow
✔  success   Clean success
ℹ  info      Rebuild since file changed
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gg-editor@3.1.1 start: `node ./scripts/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gg-editor@3.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanghongyue/.npm/_logs/2020-04-15T03_50_13_918Z-debug.log

手动把8080端口kill掉（lsof -i:8080   &&   sudo kill -9 xxxxx），再运行npm start还是会报这个错。

**Comment by gaoli** [comment]
@whyyue 试用 3.1.1 版本看看，或者直接在 [官网](https://ggeditor.com/) 查看在线 Demo :)

**Comment by whyyue** [comment]
@gaoli 当前版本就是3.1.1。。

**Comment by gaoli** [comment]
@whyyue 应该不是最新的版本，最新的版本已经使用 [dumi](https://github.com/umijs/dumi) 替代，你可以重新 clone 一份代码，执行 `npm start` 试下，效果应该跟 [官网](https://ggeditor.com/) 一样：）
